"""update_bookings

Revision ID: 6736661765de
Revises: 72a2d61c21d4
Create Date: 2026-06-10 13:38:22.332306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6736661765de'
down_revision: Union[str, Sequence[str], None] = '72a2d61c21d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
