"""initial

Revision ID: ba2047e92599
Revises: 
Create Date: 2026-06-20 01:50:44.217464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2047e92599'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_city', sa.String(), nullable=False, comment='Город отправки'),
    sa.Column('arrival_city', sa.String(), nullable=False, comment='Город прибытия'),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False, comment='Время отправки'),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False, comment='Время прибытия'),
    sa.Column('price', sa.Float(), nullable=False, comment='Цена'),
    sa.Column('available_seats', sa.Integer(), nullable=False, comment='Кол-во посадочных мест'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False, comment='Кол-во забронированных мест'),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('passenger_name', sa.String(), nullable=False, comment='Имя пассажира'),
    sa.Column('passenger_phone', sa.String(), nullable=False, comment='Телефон пассажира'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Время создания'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
